name: Build zig.wasm

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt install -y git cargo
      - uses: actions/checkout@v3
      - name: Setup Wasmer
        uses: wasmerio/setup-wasmer@v1
      - name: Run script.sh
        shell: bash
        run: |
          pwd 
          ls
          WAPM_DEV_USERNAME=${{secrets.WAPM_DEV_USERNAME}} \
          ./script.sh
      - name: Publish to WAPM
        uses: wasmerio/wapm-publish@v1
        with:
          registry: ${{ secrets.WAPM_REGISTRY }}
          directory: ${{ secrets.WAPM_DIRECTORY }}
          username: ${{ secrets.WAPM_DEV_USERNAME }}
          password: ${{ secrets.WAPM_DEV_PASSWORD }}
